name: Build Windows EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable
      run: |
        pyinstaller ^
          --onefile ^
          --windowed ^
          --collect-all CTkColorPicker ^
          --collect-all PIL ^
          --add-data "resources;resources" ^
          EyeManager.py

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: EyeManager-Windows
        path: dist/EyeManager.exe
